FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:bullseye

RUN apt-get -q update && apt-get install -yq --no-install-recommends \
	qbittorrent \
	qbittorrent-nox \
	&& apt-get clean && rm -rf /var/lib/apt/lists/*

CMD echo y | qbittorrent-nox --webui-port=80

